title: "Shania Scripts"
description: "A personal coding blog and portfolio where I share projects, lessons, and insights from my journey into software engineering."
theme: minima

header_pages:
  - about.md
  - projects.md

author: "Shania Thomas"     # <-- make this a plain string
email: "thomasshania91@gmail.com"   # <-- move email to top-level

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/shaniascripts" }
